name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: juliangruber/read-file-action@v1
        with:
          path: ./README.md
        id: read_file
      - uses: Code-Hex/neo-cowsay-action@v1
        with:
          message: ${{ steps.readfile.outputs.content }}